- hosts: auth487
  become: true
  become_method: sudo

  vars:
    app_docker_image: "{{ lookup('ansible.builtin.env', 'APP_DOCKER_IMAGE') }}"
    internal_port: 5000
    project_environment:
      - SECRETS_DIR=/opt/secrets
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DB_NAME=auth487
      - AUTH_BASE_URL=https://{{ http_domain }}
      - AUTH_DOMAIN={{ auth_domain }}
      - AUTH_PRIVATE_KEY_FILE=/opt/secrets/auth_info/auth_key.pem
      - AUTH_PUBLIC_KEY_FILE=/opt/secrets/auth_info/auth_key.pub.pem
      - AUTH_INFO_FILE=/opt/secrets/auth_info/auth_info.json
      - NOTIFICATION_EMAIL_FROM={{ notification_from }}
      - NOTIFICATION_EMAIL_TO={{ notification_to }}
      - GMAIL_CREDENTIALS_FILE=/opt/secrets/gmail_sender/gmail_credentials.json

  roles:
    - https-site
    - docker-compose-project
