#!/usr/bin/env bash
set -e -o pipefail

cur_dir="$(cd "$(dirname "$0")" && pwd)"
project_dir="$cur_dir/.."

source "$project_dir/.dev/common.sh"
export AUTH_MONGO_DB_NAME='auth487_docker_test'
web_port=6000

docker run -d --rm --name auth487-test --link dev-mongo \
    -v "$HOME/.private:/usr/local/private" \
    -v "$project_dir/.dev:/usr/local/dev" \
    -e 'AUTH_PRIVATE_KEY_FILE=/usr/local/private/auth487/private_key.pem' \
    -e 'AUTH_PUBLIC_KEY_FILE=/usr/local/private/auth487/public_key.pem' \
    -e 'AUTH_INFO_FILE=/usr/local/dev/test-auth-info.json' \
    -e "AUTH_DOMAIN=http://localhost:$web_port" \
    -e 'FLASK_APP=app.py' \
    -e 'FLASK_ENV=dev' \
    -e 'FLASK_DEBUG=1' \
    -e 'MONGO_HOST=dev-mongo' \
    -e "AUTH_MONGO_DB_NAME=$AUTH_MONGO_DB_NAME" \
    -p "127.0.0.1:$web_port:5000" \
    -ti \
    'andre487/auth487:latest' > /dev/null

sleep 2

docker logs -f auth487-test &> "/tmp/auth487-test.log" &

test_auth_token="$(cat "$project_dir/.dev/test-auth-token.txt")"
test_csrf_token="$(cat "$project_dir/.dev/test-csrf-token.txt")"
test_vars="{
    'test_auth_token': '$test_auth_token',
    'test_csrf_token': '$test_csrf_token',
    'test_port': '$web_port',
}"

"$dev_env/bin/python" "$project_dir/.dev/manage-db.py" setup
set +e
"$dev_env/bin/pyresttest" "http://127.0.0.1:$web_port" "$project_dir/endpoint-specs.yml" --vars="$test_vars"
result="$?"
set -e
"$dev_env/bin/python" "$project_dir/.dev/manage-db.py" tear-down

docker stop auth487-test > /dev/null

exit "$result"
